# database 연동 설정
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/shopingmall # 자신의 환경에 맞게 변경 가능
    username: root # 자신의 환경에 맞게 변경 가능
    password: 1234 # 자신의 환경에 맞게 변경 가능



  # 임의로 설정한 변수
  # spring security에서 JWT 토큰 만들때 사용
  jwt:
    secret: eliceproject2eliceproject2eliceproject2eliceproject2



  # spring data jpa 설정
  jpa:
    hibernate:
      ddl-auto: create # create 처음 실행시 sql 테이블 생성 이후에는 none 으로 설정
    show-sql: true
    defer-datasource-initialization: true